/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SkyeliteRouteImport } from './routes/skyelite'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressKitRouteImport } from './routes/press-kit'
import { Route as PortfolioOsRouteImport } from './routes/portfolio-os'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OpenSourceRouteImport } from './routes/open-source'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LegendsRouteImport } from './routes/legends'
import { Route as InvestorRouteImport } from './routes/investor'
import { Route as HaloRouteImport } from './routes/halo'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CvRouteImport } from './routes/cv'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BookRouteImport } from './routes/book'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkyeliteIndexRouteImport } from './routes/skyelite.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as PortfolioOsIndexRouteImport } from './routes/portfolio-os.index'
import { Route as LegendsIndexRouteImport } from './routes/legends.index'
import { Route as InvestorIndexRouteImport } from './routes/investor.index'
import { Route as CargoxIndexRouteImport } from './routes/cargox.index'
import { Route as WorkTaskoraRouteImport } from './routes/work.taskora'
import { Route as WorkIosRouteImport } from './routes/work.ios'
import { Route as WorkDeckRouteImport } from './routes/work.deck'
import { Route as WorkDatacoreRouteImport } from './routes/work.datacore'
import { Route as WorkAuraiRouteImport } from './routes/work.aurai'
import { Route as WorkAeonRouteImport } from './routes/work.aeon'
import { Route as SkyeliteStoryRouteImport } from './routes/skyelite.story'
import { Route as SkyeliteRatesRouteImport } from './routes/skyelite.rates'
import { Route as SkyeliteFaqRouteImport } from './routes/skyelite.faq'
import { Route as SkyeliteBookRouteImport } from './routes/skyelite.book'
import { Route as SkyeliteBenefitsRouteImport } from './routes/skyelite.benefits'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as PortfolioOsSuiteRouteImport } from './routes/portfolio-os.suite'
import { Route as PortfolioOsSlugRouteImport } from './routes/portfolio-os.$slug'
import { Route as LegendsSlugRouteImport } from './routes/legends.$slug'
import { Route as LandingSlugRouteImport } from './routes/landing.$slug'
import { Route as InvestorSlugRouteImport } from './routes/investor.$slug'
import { Route as ExploreSlugRouteImport } from './routes/explore.$slug'
import { Route as CargoxSlugRouteImport } from './routes/cargox.$slug'
import { Route as ApiPublicMediaKeyRouteImport } from './routes/api/public/media.$key'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SkyeliteRoute = SkyeliteRouteImport.update({
  id: '/skyelite',
  path: '/skyelite',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressKitRoute = PressKitRouteImport.update({
  id: '/press-kit',
  path: '/press-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioOsRoute = PortfolioOsRouteImport.update({
  id: '/portfolio-os',
  path: '/portfolio-os',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSourceRoute = OpenSourceRouteImport.update({
  id: '/open-source',
  path: '/open-source',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LegendsRoute = LegendsRouteImport.update({
  id: '/legends',
  path: '/legends',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorRoute = InvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const HaloRoute = HaloRouteImport.update({
  id: '/halo',
  path: '/halo',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkyeliteIndexRoute = SkyeliteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkyeliteRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioOsIndexRoute = PortfolioOsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioOsRoute,
} as any)
const LegendsIndexRoute = LegendsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegendsRoute,
} as any)
const InvestorIndexRoute = InvestorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvestorRoute,
} as any)
const CargoxIndexRoute = CargoxIndexRouteImport.update({
  id: '/cargox/',
  path: '/cargox/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkTaskoraRoute = WorkTaskoraRouteImport.update({
  id: '/work/taskora',
  path: '/work/taskora',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIosRoute = WorkIosRouteImport.update({
  id: '/work/ios',
  path: '/work/ios',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkDeckRoute = WorkDeckRouteImport.update({
  id: '/work/deck',
  path: '/work/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkDatacoreRoute = WorkDatacoreRouteImport.update({
  id: '/work/datacore',
  path: '/work/datacore',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkAuraiRoute = WorkAuraiRouteImport.update({
  id: '/work/aurai',
  path: '/work/aurai',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkAeonRoute = WorkAeonRouteImport.update({
  id: '/work/aeon',
  path: '/work/aeon',
  getParentRoute: () => rootRouteImport,
} as any)
const SkyeliteStoryRoute = SkyeliteStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => SkyeliteRoute,
} as any)
const SkyeliteRatesRoute = SkyeliteRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => SkyeliteRoute,
} as any)
const SkyeliteFaqRoute = SkyeliteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SkyeliteRoute,
} as any)
const SkyeliteBookRoute = SkyeliteBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => SkyeliteRoute,
} as any)
const SkyeliteBenefitsRoute = SkyeliteBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => SkyeliteRoute,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioOsSuiteRoute = PortfolioOsSuiteRouteImport.update({
  id: '/suite',
  path: '/suite',
  getParentRoute: () => PortfolioOsRoute,
} as any)
const PortfolioOsSlugRoute = PortfolioOsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioOsRoute,
} as any)
const LegendsSlugRoute = LegendsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LegendsRoute,
} as any)
const LandingSlugRoute = LandingSlugRouteImport.update({
  id: '/landing/$slug',
  path: '/landing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorSlugRoute = InvestorSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InvestorRoute,
} as any)
const ExploreSlugRoute = ExploreSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExploreRoute,
} as any)
const CargoxSlugRoute = CargoxSlugRouteImport.update({
  id: '/cargox/$slug',
  path: '/cargox/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaKeyRoute = ApiPublicMediaKeyRouteImport.update({
  id: '/api/public/media/$key',
  path: '/api/public/media/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/case-studies': typeof CaseStudiesRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/cv': typeof CvRoute
  '/explore': typeof ExploreRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/halo': typeof HaloRoute
  '/investor': typeof InvestorRouteWithChildren
  '/legends': typeof LegendsRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/open-source': typeof OpenSourceRoute
  '/portfolio': typeof PortfolioRoute
  '/portfolio-os': typeof PortfolioOsRouteWithChildren
  '/press-kit': typeof PressKitRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/skills': typeof SkillsRoute
  '/skyelite': typeof SkyeliteRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/cargox/$slug': typeof CargoxSlugRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/investor/$slug': typeof InvestorSlugRoute
  '/landing/$slug': typeof LandingSlugRoute
  '/legends/$slug': typeof LegendsSlugRoute
  '/portfolio-os/$slug': typeof PortfolioOsSlugRoute
  '/portfolio-os/suite': typeof PortfolioOsSuiteRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/site/$slug': typeof SiteSlugRoute
  '/skyelite/benefits': typeof SkyeliteBenefitsRoute
  '/skyelite/book': typeof SkyeliteBookRoute
  '/skyelite/faq': typeof SkyeliteFaqRoute
  '/skyelite/rates': typeof SkyeliteRatesRoute
  '/skyelite/story': typeof SkyeliteStoryRoute
  '/work/aeon': typeof WorkAeonRoute
  '/work/aurai': typeof WorkAuraiRoute
  '/work/datacore': typeof WorkDatacoreRoute
  '/work/deck': typeof WorkDeckRoute
  '/work/ios': typeof WorkIosRoute
  '/work/taskora': typeof WorkTaskoraRoute
  '/cargox/': typeof CargoxIndexRoute
  '/investor/': typeof InvestorIndexRoute
  '/legends/': typeof LegendsIndexRoute
  '/portfolio-os/': typeof PortfolioOsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/skyelite/': typeof SkyeliteIndexRoute
  '/api/public/media/$key': typeof ApiPublicMediaKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/case-studies': typeof CaseStudiesRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/cv': typeof CvRoute
  '/explore': typeof ExploreRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/halo': typeof HaloRoute
  '/marketplace': typeof MarketplaceRoute
  '/open-source': typeof OpenSourceRoute
  '/portfolio': typeof PortfolioRoute
  '/press-kit': typeof PressKitRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/skills': typeof SkillsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/cargox/$slug': typeof CargoxSlugRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/investor/$slug': typeof InvestorSlugRoute
  '/landing/$slug': typeof LandingSlugRoute
  '/legends/$slug': typeof LegendsSlugRoute
  '/portfolio-os/$slug': typeof PortfolioOsSlugRoute
  '/portfolio-os/suite': typeof PortfolioOsSuiteRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/site/$slug': typeof SiteSlugRoute
  '/skyelite/benefits': typeof SkyeliteBenefitsRoute
  '/skyelite/book': typeof SkyeliteBookRoute
  '/skyelite/faq': typeof SkyeliteFaqRoute
  '/skyelite/rates': typeof SkyeliteRatesRoute
  '/skyelite/story': typeof SkyeliteStoryRoute
  '/work/aeon': typeof WorkAeonRoute
  '/work/aurai': typeof WorkAuraiRoute
  '/work/datacore': typeof WorkDatacoreRoute
  '/work/deck': typeof WorkDeckRoute
  '/work/ios': typeof WorkIosRoute
  '/work/taskora': typeof WorkTaskoraRoute
  '/cargox': typeof CargoxIndexRoute
  '/investor': typeof InvestorIndexRoute
  '/legends': typeof LegendsIndexRoute
  '/portfolio-os': typeof PortfolioOsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/skyelite': typeof SkyeliteIndexRoute
  '/api/public/media/$key': typeof ApiPublicMediaKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/case-studies': typeof CaseStudiesRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/cv': typeof CvRoute
  '/explore': typeof ExploreRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/halo': typeof HaloRoute
  '/investor': typeof InvestorRouteWithChildren
  '/legends': typeof LegendsRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/open-source': typeof OpenSourceRoute
  '/portfolio': typeof PortfolioRoute
  '/portfolio-os': typeof PortfolioOsRouteWithChildren
  '/press-kit': typeof PressKitRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/skills': typeof SkillsRoute
  '/skyelite': typeof SkyeliteRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/cargox/$slug': typeof CargoxSlugRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/investor/$slug': typeof InvestorSlugRoute
  '/landing/$slug': typeof LandingSlugRoute
  '/legends/$slug': typeof LegendsSlugRoute
  '/portfolio-os/$slug': typeof PortfolioOsSlugRoute
  '/portfolio-os/suite': typeof PortfolioOsSuiteRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/site/$slug': typeof SiteSlugRoute
  '/skyelite/benefits': typeof SkyeliteBenefitsRoute
  '/skyelite/book': typeof SkyeliteBookRoute
  '/skyelite/faq': typeof SkyeliteFaqRoute
  '/skyelite/rates': typeof SkyeliteRatesRoute
  '/skyelite/story': typeof SkyeliteStoryRoute
  '/work/aeon': typeof WorkAeonRoute
  '/work/aurai': typeof WorkAuraiRoute
  '/work/datacore': typeof WorkDatacoreRoute
  '/work/deck': typeof WorkDeckRoute
  '/work/ios': typeof WorkIosRoute
  '/work/taskora': typeof WorkTaskoraRoute
  '/cargox/': typeof CargoxIndexRoute
  '/investor/': typeof InvestorIndexRoute
  '/legends/': typeof LegendsIndexRoute
  '/portfolio-os/': typeof PortfolioOsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/skyelite/': typeof SkyeliteIndexRoute
  '/api/public/media/$key': typeof ApiPublicMediaKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/book'
    | '/case-studies'
    | '/certifications'
    | '/contact'
    | '/cv'
    | '/explore'
    | '/faqs'
    | '/halo'
    | '/investor'
    | '/legends'
    | '/marketplace'
    | '/open-source'
    | '/portfolio'
    | '/portfolio-os'
    | '/press-kit'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/skills'
    | '/skyelite'
    | '/testimonials'
    | '/thank-you'
    | '/cargox/$slug'
    | '/explore/$slug'
    | '/investor/$slug'
    | '/landing/$slug'
    | '/legends/$slug'
    | '/portfolio-os/$slug'
    | '/portfolio-os/suite'
    | '/projects/$slug'
    | '/site/$slug'
    | '/skyelite/benefits'
    | '/skyelite/book'
    | '/skyelite/faq'
    | '/skyelite/rates'
    | '/skyelite/story'
    | '/work/aeon'
    | '/work/aurai'
    | '/work/datacore'
    | '/work/deck'
    | '/work/ios'
    | '/work/taskora'
    | '/cargox/'
    | '/investor/'
    | '/legends/'
    | '/portfolio-os/'
    | '/projects/'
    | '/skyelite/'
    | '/api/public/media/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog'
    | '/book'
    | '/case-studies'
    | '/certifications'
    | '/contact'
    | '/cv'
    | '/explore'
    | '/faqs'
    | '/halo'
    | '/marketplace'
    | '/open-source'
    | '/portfolio'
    | '/press-kit'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/skills'
    | '/testimonials'
    | '/thank-you'
    | '/cargox/$slug'
    | '/explore/$slug'
    | '/investor/$slug'
    | '/landing/$slug'
    | '/legends/$slug'
    | '/portfolio-os/$slug'
    | '/portfolio-os/suite'
    | '/projects/$slug'
    | '/site/$slug'
    | '/skyelite/benefits'
    | '/skyelite/book'
    | '/skyelite/faq'
    | '/skyelite/rates'
    | '/skyelite/story'
    | '/work/aeon'
    | '/work/aurai'
    | '/work/datacore'
    | '/work/deck'
    | '/work/ios'
    | '/work/taskora'
    | '/cargox'
    | '/investor'
    | '/legends'
    | '/portfolio-os'
    | '/projects'
    | '/skyelite'
    | '/api/public/media/$key'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/book'
    | '/case-studies'
    | '/certifications'
    | '/contact'
    | '/cv'
    | '/explore'
    | '/faqs'
    | '/halo'
    | '/investor'
    | '/legends'
    | '/marketplace'
    | '/open-source'
    | '/portfolio'
    | '/portfolio-os'
    | '/press-kit'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/skills'
    | '/skyelite'
    | '/testimonials'
    | '/thank-you'
    | '/cargox/$slug'
    | '/explore/$slug'
    | '/investor/$slug'
    | '/landing/$slug'
    | '/legends/$slug'
    | '/portfolio-os/$slug'
    | '/portfolio-os/suite'
    | '/projects/$slug'
    | '/site/$slug'
    | '/skyelite/benefits'
    | '/skyelite/book'
    | '/skyelite/faq'
    | '/skyelite/rates'
    | '/skyelite/story'
    | '/work/aeon'
    | '/work/aurai'
    | '/work/datacore'
    | '/work/deck'
    | '/work/ios'
    | '/work/taskora'
    | '/cargox/'
    | '/investor/'
    | '/legends/'
    | '/portfolio-os/'
    | '/projects/'
    | '/skyelite/'
    | '/api/public/media/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  BookRoute: typeof BookRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  CertificationsRoute: typeof CertificationsRoute
  ContactRoute: typeof ContactRoute
  CvRoute: typeof CvRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  FaqsRoute: typeof FaqsRoute
  HaloRoute: typeof HaloRoute
  InvestorRoute: typeof InvestorRouteWithChildren
  LegendsRoute: typeof LegendsRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRoute
  OpenSourceRoute: typeof OpenSourceRoute
  PortfolioRoute: typeof PortfolioRoute
  PortfolioOsRoute: typeof PortfolioOsRouteWithChildren
  PressKitRoute: typeof PressKitRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  SkillsRoute: typeof SkillsRoute
  SkyeliteRoute: typeof SkyeliteRouteWithChildren
  TestimonialsRoute: typeof TestimonialsRoute
  ThankYouRoute: typeof ThankYouRoute
  CargoxSlugRoute: typeof CargoxSlugRoute
  LandingSlugRoute: typeof LandingSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  SiteSlugRoute: typeof SiteSlugRoute
  WorkAeonRoute: typeof WorkAeonRoute
  WorkAuraiRoute: typeof WorkAuraiRoute
  WorkDatacoreRoute: typeof WorkDatacoreRoute
  WorkDeckRoute: typeof WorkDeckRoute
  WorkIosRoute: typeof WorkIosRoute
  WorkTaskoraRoute: typeof WorkTaskoraRoute
  CargoxIndexRoute: typeof CargoxIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiPublicMediaKeyRoute: typeof ApiPublicMediaKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skyelite': {
      id: '/skyelite'
      path: '/skyelite'
      fullPath: '/skyelite'
      preLoaderRoute: typeof SkyeliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press-kit': {
      id: '/press-kit'
      path: '/press-kit'
      fullPath: '/press-kit'
      preLoaderRoute: typeof PressKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-os': {
      id: '/portfolio-os'
      path: '/portfolio-os'
      fullPath: '/portfolio-os'
      preLoaderRoute: typeof PortfolioOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source': {
      id: '/open-source'
      path: '/open-source'
      fullPath: '/open-source'
      preLoaderRoute: typeof OpenSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legends': {
      id: '/legends'
      path: '/legends'
      fullPath: '/legends'
      preLoaderRoute: typeof LegendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor': {
      id: '/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof InvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halo': {
      id: '/halo'
      path: '/halo'
      fullPath: '/halo'
      preLoaderRoute: typeof HaloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skyelite/': {
      id: '/skyelite/'
      path: '/'
      fullPath: '/skyelite/'
      preLoaderRoute: typeof SkyeliteIndexRouteImport
      parentRoute: typeof SkyeliteRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-os/': {
      id: '/portfolio-os/'
      path: '/'
      fullPath: '/portfolio-os/'
      preLoaderRoute: typeof PortfolioOsIndexRouteImport
      parentRoute: typeof PortfolioOsRoute
    }
    '/legends/': {
      id: '/legends/'
      path: '/'
      fullPath: '/legends/'
      preLoaderRoute: typeof LegendsIndexRouteImport
      parentRoute: typeof LegendsRoute
    }
    '/investor/': {
      id: '/investor/'
      path: '/'
      fullPath: '/investor/'
      preLoaderRoute: typeof InvestorIndexRouteImport
      parentRoute: typeof InvestorRoute
    }
    '/cargox/': {
      id: '/cargox/'
      path: '/cargox'
      fullPath: '/cargox/'
      preLoaderRoute: typeof CargoxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/taskora': {
      id: '/work/taskora'
      path: '/work/taskora'
      fullPath: '/work/taskora'
      preLoaderRoute: typeof WorkTaskoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/ios': {
      id: '/work/ios'
      path: '/work/ios'
      fullPath: '/work/ios'
      preLoaderRoute: typeof WorkIosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/deck': {
      id: '/work/deck'
      path: '/work/deck'
      fullPath: '/work/deck'
      preLoaderRoute: typeof WorkDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/datacore': {
      id: '/work/datacore'
      path: '/work/datacore'
      fullPath: '/work/datacore'
      preLoaderRoute: typeof WorkDatacoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/aurai': {
      id: '/work/aurai'
      path: '/work/aurai'
      fullPath: '/work/aurai'
      preLoaderRoute: typeof WorkAuraiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/aeon': {
      id: '/work/aeon'
      path: '/work/aeon'
      fullPath: '/work/aeon'
      preLoaderRoute: typeof WorkAeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skyelite/story': {
      id: '/skyelite/story'
      path: '/story'
      fullPath: '/skyelite/story'
      preLoaderRoute: typeof SkyeliteStoryRouteImport
      parentRoute: typeof SkyeliteRoute
    }
    '/skyelite/rates': {
      id: '/skyelite/rates'
      path: '/rates'
      fullPath: '/skyelite/rates'
      preLoaderRoute: typeof SkyeliteRatesRouteImport
      parentRoute: typeof SkyeliteRoute
    }
    '/skyelite/faq': {
      id: '/skyelite/faq'
      path: '/faq'
      fullPath: '/skyelite/faq'
      preLoaderRoute: typeof SkyeliteFaqRouteImport
      parentRoute: typeof SkyeliteRoute
    }
    '/skyelite/book': {
      id: '/skyelite/book'
      path: '/book'
      fullPath: '/skyelite/book'
      preLoaderRoute: typeof SkyeliteBookRouteImport
      parentRoute: typeof SkyeliteRoute
    }
    '/skyelite/benefits': {
      id: '/skyelite/benefits'
      path: '/benefits'
      fullPath: '/skyelite/benefits'
      preLoaderRoute: typeof SkyeliteBenefitsRouteImport
      parentRoute: typeof SkyeliteRoute
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-os/suite': {
      id: '/portfolio-os/suite'
      path: '/suite'
      fullPath: '/portfolio-os/suite'
      preLoaderRoute: typeof PortfolioOsSuiteRouteImport
      parentRoute: typeof PortfolioOsRoute
    }
    '/portfolio-os/$slug': {
      id: '/portfolio-os/$slug'
      path: '/$slug'
      fullPath: '/portfolio-os/$slug'
      preLoaderRoute: typeof PortfolioOsSlugRouteImport
      parentRoute: typeof PortfolioOsRoute
    }
    '/legends/$slug': {
      id: '/legends/$slug'
      path: '/$slug'
      fullPath: '/legends/$slug'
      preLoaderRoute: typeof LegendsSlugRouteImport
      parentRoute: typeof LegendsRoute
    }
    '/landing/$slug': {
      id: '/landing/$slug'
      path: '/landing/$slug'
      fullPath: '/landing/$slug'
      preLoaderRoute: typeof LandingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor/$slug': {
      id: '/investor/$slug'
      path: '/$slug'
      fullPath: '/investor/$slug'
      preLoaderRoute: typeof InvestorSlugRouteImport
      parentRoute: typeof InvestorRoute
    }
    '/explore/$slug': {
      id: '/explore/$slug'
      path: '/$slug'
      fullPath: '/explore/$slug'
      preLoaderRoute: typeof ExploreSlugRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/cargox/$slug': {
      id: '/cargox/$slug'
      path: '/cargox/$slug'
      fullPath: '/cargox/$slug'
      preLoaderRoute: typeof CargoxSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$key': {
      id: '/api/public/media/$key'
      path: '/api/public/media/$key'
      fullPath: '/api/public/media/$key'
      preLoaderRoute: typeof ApiPublicMediaKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExploreRouteChildren {
  ExploreSlugRoute: typeof ExploreSlugRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreSlugRoute: ExploreSlugRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface InvestorRouteChildren {
  InvestorSlugRoute: typeof InvestorSlugRoute
  InvestorIndexRoute: typeof InvestorIndexRoute
}

const InvestorRouteChildren: InvestorRouteChildren = {
  InvestorSlugRoute: InvestorSlugRoute,
  InvestorIndexRoute: InvestorIndexRoute,
}

const InvestorRouteWithChildren = InvestorRoute._addFileChildren(
  InvestorRouteChildren,
)

interface LegendsRouteChildren {
  LegendsSlugRoute: typeof LegendsSlugRoute
  LegendsIndexRoute: typeof LegendsIndexRoute
}

const LegendsRouteChildren: LegendsRouteChildren = {
  LegendsSlugRoute: LegendsSlugRoute,
  LegendsIndexRoute: LegendsIndexRoute,
}

const LegendsRouteWithChildren =
  LegendsRoute._addFileChildren(LegendsRouteChildren)

interface PortfolioOsRouteChildren {
  PortfolioOsSlugRoute: typeof PortfolioOsSlugRoute
  PortfolioOsSuiteRoute: typeof PortfolioOsSuiteRoute
  PortfolioOsIndexRoute: typeof PortfolioOsIndexRoute
}

const PortfolioOsRouteChildren: PortfolioOsRouteChildren = {
  PortfolioOsSlugRoute: PortfolioOsSlugRoute,
  PortfolioOsSuiteRoute: PortfolioOsSuiteRoute,
  PortfolioOsIndexRoute: PortfolioOsIndexRoute,
}

const PortfolioOsRouteWithChildren = PortfolioOsRoute._addFileChildren(
  PortfolioOsRouteChildren,
)

interface SkyeliteRouteChildren {
  SkyeliteBenefitsRoute: typeof SkyeliteBenefitsRoute
  SkyeliteBookRoute: typeof SkyeliteBookRoute
  SkyeliteFaqRoute: typeof SkyeliteFaqRoute
  SkyeliteRatesRoute: typeof SkyeliteRatesRoute
  SkyeliteStoryRoute: typeof SkyeliteStoryRoute
  SkyeliteIndexRoute: typeof SkyeliteIndexRoute
}

const SkyeliteRouteChildren: SkyeliteRouteChildren = {
  SkyeliteBenefitsRoute: SkyeliteBenefitsRoute,
  SkyeliteBookRoute: SkyeliteBookRoute,
  SkyeliteFaqRoute: SkyeliteFaqRoute,
  SkyeliteRatesRoute: SkyeliteRatesRoute,
  SkyeliteStoryRoute: SkyeliteStoryRoute,
  SkyeliteIndexRoute: SkyeliteIndexRoute,
}

const SkyeliteRouteWithChildren = SkyeliteRoute._addFileChildren(
  SkyeliteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  BookRoute: BookRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  CertificationsRoute: CertificationsRoute,
  ContactRoute: ContactRoute,
  CvRoute: CvRoute,
  ExploreRoute: ExploreRouteWithChildren,
  FaqsRoute: FaqsRoute,
  HaloRoute: HaloRoute,
  InvestorRoute: InvestorRouteWithChildren,
  LegendsRoute: LegendsRouteWithChildren,
  MarketplaceRoute: MarketplaceRoute,
  OpenSourceRoute: OpenSourceRoute,
  PortfolioRoute: PortfolioRoute,
  PortfolioOsRoute: PortfolioOsRouteWithChildren,
  PressKitRoute: PressKitRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  SkillsRoute: SkillsRoute,
  SkyeliteRoute: SkyeliteRouteWithChildren,
  TestimonialsRoute: TestimonialsRoute,
  ThankYouRoute: ThankYouRoute,
  CargoxSlugRoute: CargoxSlugRoute,
  LandingSlugRoute: LandingSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  SiteSlugRoute: SiteSlugRoute,
  WorkAeonRoute: WorkAeonRoute,
  WorkAuraiRoute: WorkAuraiRoute,
  WorkDatacoreRoute: WorkDatacoreRoute,
  WorkDeckRoute: WorkDeckRoute,
  WorkIosRoute: WorkIosRoute,
  WorkTaskoraRoute: WorkTaskoraRoute,
  CargoxIndexRoute: CargoxIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiPublicMediaKeyRoute: ApiPublicMediaKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
